/**
 * Copyright (c) 2026 Shiva Deore (Taracod).
 * Licensed under AGPL-3.0. See LICENSE for details.
 */

import { createHash, randomBytes } from 'node:crypto';
import path from 'node:path';

import type { Db } from '../daemon/db/connection';
import type { AttemptRecord, JobRecord } from '../daemon/jobEngine';
import type { RepositorySnapshotAuthority, RepositorySnapshotEntry } from './repositorySnapshotAuthority';

export type RepositoryUnderstandingKind =
  | 'file' | 'language' | 'classification' | 'manifest' | 'workspace'
  | 'package_manager' | 'import' | 'symbol' | 'test_hint' | 'command'
  | 'ci' | 'instruction';

export interface RepositoryUnderstandingRecord {
  recordId: string;
  snapshotId: string;
  kind: RepositoryUnderstandingKind;
  key: string;
  sourcePath: string | null;
  sourceHash: string | null;
  payload: Record<string, unknown>;
  reusedFromSnapshotId: string | null;
  createdAt: number;
  stale: boolean;
}

export interface RepositorySourceReference {
  path: string;
  lineStart: number;
  lineEnd: number;
}

export interface RepositoryArchitectureNote {
  noteId: string;
  jobId: string;
  attemptId: string;
  generation: number;
  repositorySnapshotId: string;
  statement: string;
  sourceReferences: RepositorySourceReference[];
  createdAt: number;
}

export interface RepositoryUnderstandingIndex {
  snapshotId: string;
  stateDigest: string;
  createdCount: number;
  reusedCount: number;
  indexedAt: number;
  stale: boolean;
}

export interface RepositoryUnderstandingAuthority {
  indexSnapshot(input: {
    jobId: string;
    attemptId: string;
    generation: number;
    fenceToken: string;
    repositorySnapshotId: string;
    producer: string;
    now?: number;
  }): Promise<RepositoryUnderstandingIndex>;
  listRecords(snapshotId: string, kind?: RepositoryUnderstandingKind): RepositoryUnderstandingRecord[];
  search(snapshotId: string, query: string, options?: { limit?: number }): Promise<{
    snapshotId: string;
    stateDigest: string;
    records: RepositoryUnderstandingRecord[];
    lexicalMatches: Array<{ path: string; line: number; column: number; text: string }>;
    truncated: boolean;
    stale: boolean;
  }>;
  addArchitectureNote(input: {
    jobId: string;
    attemptId: string;
    generation: number;
    fenceToken: string;
    repositorySnapshotId: string;
    statement: string;
    sourceReferences: RepositorySourceReference[];
    producer: string;
    now?: number;
  }): RepositoryArchitectureNote;
  listArchitectureNotes(snapshotId: string): RepositoryArchitectureNote[];
}

export class RepositoryUnderstandingError extends Error {
  constructor(readonly code: string, message: string) {
    super(message);
    this.name = 'RepositoryUnderstandingError';
  }
}

interface Deps {
  db: Db;
  repository: RepositorySnapshotAuthority;
  getJob(jobId: string): JobRecord | null;
  getAttempt(attemptId: string): AttemptRecord | null;
  appendJobEvent(command: {
    jobId: string;
    attemptId: string;
    generation: number;
    type: string;
    payload?: Record<string, unknown> | null;
    producer: string;
    idempotencyKey: string;
  }): { applied: boolean; duplicate: boolean; conflict?: string };
}

interface DerivedFact {
  kind: RepositoryUnderstandingKind;
  key: string;
  sourcePath: string | null;
  sourceHash: string | null;
  payload: Record<string, unknown>;
}

const PERMISSION_ESCALATION = /\b(?:disable|bypass|skip|ignore|remove)\b.{0,48}\b(?:approval|permission|sandbox|policy|guard)|\ballow\s+all\b/i;
const GENERATED_PATH = /(?:^|\/)(?:generated|gen|dist|build|coverage|vendor)(?:\/|$)|(?:\.generated|\.gen)\.[^.\/]+$/i;
const GENERATED_HEADER = /\b(?:generated (?:file|code)|do not edit|autogenerated)\b/i;
const VENDOR_PATH = /(?:^|\/)(?:vendor|third_party|node_modules)(?:\/|$)/i;

function digest(value: unknown): string {
  return createHash('sha256').update(JSON.stringify(value)).digest('hex');
}

function normalizeRelative(value: string): string {
  return value.split(path.sep).join('/').replace(/^\.\//, '');
}

function languageFor(relativePath: string): string | null {
  const name = relativePath.toLowerCase();
  if (/\.tsx?$/.test(name)) return 'typescript';
  if (/\.jsx?$/.test(name)) return 'javascript';
  if (/\.py$/.test(name)) return 'python';
  if (/\.go$/.test(name)) return 'go';
  if (/\.rs$/.test(name)) return 'rust';
  if (/\.java$/.test(name)) return 'java';
  if (/\.cs$/.test(name)) return 'csharp';
  if (/\.rb$/.test(name)) return 'ruby';
  if (/\.(?:c|h|cc|cpp|hpp)$/.test(name)) return 'cpp';
  if (/\.sh$/.test(name)) return 'shell';
  if (/\.ps1$/.test(name)) return 'powershell';
  if (/\.json$/.test(name)) return 'json';
  if (/\.ya?ml$/.test(name)) return 'yaml';
  if (/\.toml$/.test(name)) return 'toml';
  if (/\.md$/.test(name)) return 'markdown';
  return null;
}

function packageManagerFor(relativePath: string): string | null {
  switch (path.posix.basename(relativePath)) {
    case 'package-lock.json': return 'npm';
    case 'pnpm-lock.yaml': return 'pnpm';
    case 'yarn.lock': return 'yarn';
    case 'bun.lock':
    case 'bun.lockb': return 'bun';
    case 'uv.lock': return 'uv';
    case 'poetry.lock': return 'poetry';
    case 'Cargo.lock': return 'cargo';
    case 'go.sum': return 'go';
    default: return null;
  }
}

function lineOf(content: string, offset: number): number {
  return content.slice(0, offset).split('\n').length;
}

function importFacts(relativePath: string, language: string, content: string, sourceHash: string): DerivedFact[] {
  const facts: DerivedFact[] = [];
  const add = (specifier: string, offset: number): void => {
    facts.push({
      kind: 'import', key: `${relativePath}:${specifier}:${lineOf(content, offset)}`,
      sourcePath: relativePath, sourceHash,
      payload: { specifier, line: lineOf(content, offset), language },
    });
  };
  if (language === 'typescript' || language === 'javascript') {
    const expression = /(?:\b(?:import|export)\b[^'"\n]*?\bfrom\s*|\brequire\s*\()\s*['"]([^'"]+)['"]/g;
    for (const match of content.matchAll(expression)) add(match[1]!, match.index ?? 0);
  } else if (language === 'python') {
    const expression = /^\s*(?:from\s+([\w.]+)\s+import|import\s+([\w.]+))/gm;
    for (const match of content.matchAll(expression)) add(match[1] ?? match[2]!, match.index ?? 0);
  } else if (language === 'go') {
    const expression = /import\s+(?:\w+\s+)?"([^"]+)"/g;
    for (const match of content.matchAll(expression)) add(match[1]!, match.index ?? 0);
  } else if (language === 'rust') {
    const expression = /^\s*(?:use|mod)\s+([\w:]+)/gm;
    for (const match of content.matchAll(expression)) add(match[1]!, match.index ?? 0);
  }
  return facts.slice(0, 200);
}

function symbolFacts(relativePath: string, language: string, content: string, sourceHash: string): DerivedFact[] {
  const patterns = language === 'python'
    ? [/^\s*(?:async\s+)?def\s+([A-Za-z_]\w*)/gm, /^\s*class\s+([A-Za-z_]\w*)/gm]
    : language === 'go'
      ? [/^\s*func\s+(?:\([^)]*\)\s*)?([A-Za-z_]\w*)/gm, /^\s*type\s+([A-Za-z_]\w*)/gm]
      : language === 'rust'
        ? [/^\s*(?:pub\s+)?(?:fn|struct|enum|trait|mod)\s+([A-Za-z_]\w*)/gm]
        : [
          /\b(?:export\s+)?(?:async\s+)?(?:function|class|interface|type|enum)\s+([A-Za-z_$][\w$]*)/g,
          /\b(?:export\s+)?(?:const|let|var)\s+([A-Za-z_$][\w$]*)/g,
        ];
  const seen = new Set<string>();
  const facts: DerivedFact[] = [];
  for (const expression of patterns) {
    for (const match of content.matchAll(expression)) {
      const name = match[1]!;
      const line = lineOf(content, match.index ?? 0);
      const key = `${relativePath}:${name}:${line}`;
      if (seen.has(key)) continue;
      seen.add(key);
      facts.push({ kind: 'symbol', key, sourcePath: relativePath, sourceHash, payload: { name, line, language } });
      if (facts.length >= 200) return facts;
    }
  }
  return facts;
}

function recordId(fact: DerivedFact): string {
  return `repository_fact_${digest({
    kind: fact.kind, key: fact.key, sourcePath: fact.sourcePath,
    sourceHash: fact.sourceHash, payload: fact.payload,
  })}`;
}

export function createRepositoryUnderstandingAuthority(deps: Deps): RepositoryUnderstandingAuthority {
  const { db, repository } = deps;

  const assertAuthority = (input: {
    jobId: string; attemptId: string; generation: number; fenceToken: string; repositorySnapshotId: string;
  }): void => {
    const job = deps.getJob(input.jobId);
    const attempt = deps.getAttempt(input.attemptId);
    const snapshot = repository.getSnapshot(input.repositorySnapshotId);
    const now = Date.now();
    if (!job || !attempt || !snapshot
      || snapshot.jobId !== input.jobId || snapshot.attemptId !== input.attemptId || snapshot.generation !== input.generation
      || attempt.jobId !== input.jobId || attempt.generation !== input.generation || attempt.fenceToken !== input.fenceToken
      || attempt.leaseExpiresAt === null || attempt.leaseExpiresAt <= now
      || ['succeeded', 'failed', 'cancelled', 'timed_out', 'crashed', 'unknown'].includes(attempt.status)) {
      throw new RepositoryUnderstandingError('STALE_REPOSITORY_UNDERSTANDING_AUTHORITY', 'Repository understanding authority is stale');
    }
  };

  const latestSnapshotId = (snapshotId: string): string | null => {
    const snapshot = repository.getSnapshot(snapshotId);
    if (!snapshot) return null;
    const row = db.prepare(
      `SELECT snapshot_id FROM repository_snapshots
        WHERE job_id=? AND attempt_id=? AND generation=?
        ORDER BY captured_at DESC, rowid DESC LIMIT 1`,
    ).get(snapshot.jobId, snapshot.attemptId, snapshot.generation) as { snapshot_id: string } | undefined;
    return row?.snapshot_id ?? null;
  };

  const listRecords = (snapshotId: string, kind?: RepositoryUnderstandingKind): RepositoryUnderstandingRecord[] => {
    if (!repository.getSnapshot(snapshotId)) throw new RepositoryUnderstandingError('SNAPSHOT_NOT_FOUND', 'Repository snapshot not found');
    const rows = db.prepare(
      `SELECT r.*, l.snapshot_id, l.reused_from_snapshot_id
         FROM repository_understanding_snapshot_records l
         JOIN repository_understanding_records r ON r.record_id=l.record_id
        WHERE l.snapshot_id=? ${kind ? 'AND r.kind=?' : ''}
        ORDER BY r.kind, r.record_key, r.record_id`,
    ).all(...(kind ? [snapshotId, kind] : [snapshotId])) as Array<Record<string, unknown>>;
    const stale = latestSnapshotId(snapshotId) !== snapshotId;
    return rows.map((row) => ({
      recordId: String(row.record_id), snapshotId: String(row.snapshot_id),
      kind: row.kind as RepositoryUnderstandingKind, key: String(row.record_key),
      sourcePath: row.source_path === null ? null : String(row.source_path),
      sourceHash: row.source_hash === null ? null : String(row.source_hash),
      payload: JSON.parse(String(row.payload_json)) as Record<string, unknown>,
      reusedFromSnapshotId: row.reused_from_snapshot_id === null ? null : String(row.reused_from_snapshot_id),
      createdAt: Number(row.created_at), stale,
    }));
  };

  const readText = async (snapshotId: string, entry: RepositorySnapshotEntry): Promise<string | null> => {
    if (entry.captureStatus !== 'captured' || !entry.contentHash || entry.path.endsWith('/')) return null;
    try {
      const result = await repository.readFile(snapshotId, entry.path, { limit: 1_000_000 });
      return typeof result.content === 'string' ? result.content : null;
    } catch {
      return null;
    }
  };

  const deriveFacts = async (snapshotId: string, entries: RepositorySnapshotEntry[]): Promise<DerivedFact[]> => {
    const facts: DerivedFact[] = [];
    const entryPaths = new Set(entries.map((entry) => entry.path));
    for (const entry of entries) {
      const relativePath = normalizeRelative(entry.path);
      const content = await readText(snapshotId, entry);
      const generated = GENERATED_PATH.test(relativePath) || (content !== null && GENERATED_HEADER.test(content.slice(0, 500)));
      const vendor = VENDOR_PATH.test(relativePath) || entry.classification === 'excluded_directory' && /vendor/i.test(relativePath);
      facts.push({
        kind: 'file', key: relativePath, sourcePath: relativePath, sourceHash: entry.contentHash,
        payload: {
          classification: entry.classification, captureStatus: entry.captureStatus,
          size: entry.size, mode: entry.mode, gitState: entry.gitState,
        },
      });
      facts.push({
        kind: 'classification', key: relativePath, sourcePath: relativePath, sourceHash: entry.contentHash,
        payload: { generated, vendor, editable: !generated && !vendor && entry.captureStatus === 'captured' },
      });
      const language = languageFor(relativePath);
      if (language) facts.push({ kind: 'language', key: relativePath, sourcePath: relativePath, sourceHash: entry.contentHash, payload: { language } });

      const manager = packageManagerFor(relativePath);
      if (manager) facts.push({
        kind: 'package_manager', key: `${path.posix.dirname(relativePath)}:${manager}`,
        sourcePath: relativePath, sourceHash: entry.contentHash,
        payload: { manager, workspacePath: path.posix.dirname(relativePath) === '.' ? '' : path.posix.dirname(relativePath) },
      });

      if (content === null) continue;
      if (language && ['typescript', 'javascript', 'python', 'go', 'rust'].includes(language)) {
        facts.push(...importFacts(relativePath, language, content, entry.contentHash!));
        facts.push(...symbolFacts(relativePath, language, content, entry.contentHash!));
      }

      if (/(?:^|\/)(?:__tests__\/)?[^/]+\.(?:test|spec)\.[^.]+$/i.test(relativePath)) {
        const sourcePath = relativePath
          .replace(/(^|\/)__tests__\//, '$1')
          .replace(/\.(?:test|spec)(\.[^.]+)$/i, '$1');
        facts.push({
          kind: 'test_hint', key: relativePath, sourcePath: relativePath, sourceHash: entry.contentHash,
          payload: { sourcePath: entryPaths.has(sourcePath) ? sourcePath : null, confidence: entryPaths.has(sourcePath) ? 'exact_name' : 'naming_only' },
        });
      }

      if (path.posix.basename(relativePath) === 'package.json') {
        try {
          const manifest = JSON.parse(content) as Record<string, unknown>;
          facts.push({ kind: 'manifest', key: relativePath, sourcePath: relativePath, sourceHash: entry.contentHash, payload: { type: 'package', name: typeof manifest.name === 'string' ? manifest.name : null } });
          if (typeof manifest.packageManager === 'string') {
            const managerName = manifest.packageManager.split('@')[0]!;
            facts.push({ kind: 'package_manager', key: `${path.posix.dirname(relativePath)}:${managerName}`, sourcePath: relativePath, sourceHash: entry.contentHash, payload: { manager: managerName, declared: manifest.packageManager, workspacePath: path.posix.dirname(relativePath) === '.' ? '' : path.posix.dirname(relativePath) } });
          }
          const workspaces = Array.isArray(manifest.workspaces)
            ? manifest.workspaces
            : manifest.workspaces && typeof manifest.workspaces === 'object'
              ? (manifest.workspaces as { packages?: unknown }).packages
              : [];
          if (Array.isArray(workspaces)) {
            for (const pattern of workspaces.filter((item): item is string => typeof item === 'string').slice(0, 200)) {
              facts.push({ kind: 'workspace', key: `${relativePath}:${pattern}`, sourcePath: relativePath, sourceHash: entry.contentHash, payload: { manifestPath: relativePath, pattern } });
            }
          }
          const scripts = manifest.scripts && typeof manifest.scripts === 'object' ? manifest.scripts as Record<string, unknown> : {};
          for (const [name, value] of Object.entries(scripts).slice(0, 200)) {
            if (typeof value !== 'string') continue;
            facts.push({ kind: 'command', key: `${relativePath}:script:${name}`, sourcePath: relativePath, sourceHash: entry.contentHash, payload: { name, command: `npm run ${name}`, body: value, source: 'package_script' } });
          }
        } catch {
          facts.push({ kind: 'manifest', key: relativePath, sourcePath: relativePath, sourceHash: entry.contentHash, payload: { type: 'package', parseState: 'invalid' } });
        }
      } else if (/\/(?:pyproject\.toml|Cargo\.toml)$|^(?:pyproject\.toml|Cargo\.toml|go\.mod|pom\.xml)$/i.test(relativePath)) {
        facts.push({ kind: 'manifest', key: relativePath, sourcePath: relativePath, sourceHash: entry.contentHash, payload: { type: path.posix.basename(relativePath) } });
      } else if (/^\.github\/workflows\/[^/]+\.ya?ml$/i.test(relativePath)) {
        for (const match of content.matchAll(/^\s*-?\s*run:\s*(.+?)\s*$/gm)) {
          const command = match[1]!.replace(/^['"]|['"]$/g, '');
          facts.push({ kind: 'ci', key: `${relativePath}:${lineOf(content, match.index ?? 0)}`, sourcePath: relativePath, sourceHash: entry.contentHash, payload: { command, line: lineOf(content, match.index ?? 0) } });
        }
      }
    }

    for (const instruction of repository.discoverInstructions(snapshotId)) {
      const entry = entries.find((candidate) => candidate.path === instruction.path);
      const content = entry ? await readText(snapshotId, entry) : null;
      facts.push({
        kind: 'instruction', key: instruction.path, sourcePath: instruction.path,
        sourceHash: instruction.contentHash,
        payload: {
          scope: instruction.scope, precedence: instruction.precedence,
          provenance: { snapshotId, contentHash: instruction.contentHash, trust: instruction.trust },
          permissionEffect: 'none', containsPermissionEscalationAttempt: content !== null && PERMISSION_ESCALATION.test(content),
        },
      });
    }
    return facts;
  };

  const indexRow = (snapshotId: string): RepositoryUnderstandingIndex | null => {
    const row = db.prepare('SELECT * FROM repository_understanding_indexes WHERE snapshot_id=?').get(snapshotId) as Record<string, unknown> | undefined;
    return row ? {
      snapshotId, stateDigest: String(row.state_digest), createdCount: Number(row.created_count),
      reusedCount: Number(row.reused_count), indexedAt: Number(row.indexed_at), stale: latestSnapshotId(snapshotId) !== snapshotId,
    } : null;
  };

  const authority: RepositoryUnderstandingAuthority = {
    async indexSnapshot(input) {
      assertAuthority(input);
      const snapshot = repository.getSnapshot(input.repositorySnapshotId)!;
      const inventory = await repository.inventory(snapshot.id, { limit: 5_000 });
      if (inventory.stale) throw new RepositoryUnderstandingError('STALE_REPOSITORY_SNAPSHOT', 'Cannot index a stale repository snapshot');
      const existing = indexRow(snapshot.id);
      if (existing) return existing;
      const facts = await deriveFacts(snapshot.id, inventory.entries);
      const finalInventory = await repository.inventory(snapshot.id, { limit: 1 });
      if (finalInventory.stale) throw new RepositoryUnderstandingError('STALE_REPOSITORY_SNAPSHOT', 'Repository changed while understanding was being derived');
      assertAuthority(input);
      const now = input.now ?? Date.now();
      const previousRecords = snapshot.previousSnapshotId
        ? new Set(authority.listRecords(snapshot.previousSnapshotId).map((record) => record.recordId))
        : new Set<string>();
      let createdCount = 0;
      let reusedCount = 0;
      const tx = db.transaction(() => {
        for (const fact of facts) {
          const factId = recordId(fact);
          const existed = db.prepare('SELECT 1 FROM repository_understanding_records WHERE record_id=?').get(factId) !== undefined;
          db.prepare(
            `INSERT OR IGNORE INTO repository_understanding_records
               (record_id,kind,record_key,source_path,source_hash,payload_json,created_at)
             VALUES (?,?,?,?,?,?,?)`,
          ).run(factId, fact.kind, fact.key, fact.sourcePath, fact.sourceHash, JSON.stringify(fact.payload), now);
          const reusedFrom = previousRecords.has(factId) ? snapshot.previousSnapshotId : null;
          db.prepare(
            `INSERT OR IGNORE INTO repository_understanding_snapshot_records
               (snapshot_id,record_id,reused_from_snapshot_id,created_at) VALUES (?,?,?,?)`,
          ).run(snapshot.id, factId, reusedFrom, now);
          if (reusedFrom) reusedCount += 1;
          else if (!existed) createdCount += 1;
        }
        db.prepare(
          `INSERT INTO repository_understanding_indexes
             (snapshot_id,state_digest,status,created_count,reused_count,indexed_at)
           VALUES (?,?,'completed',?,?,?)`,
        ).run(snapshot.id, snapshot.stateDigest, createdCount, reusedCount, now);
      });
      tx.immediate();
      deps.appendJobEvent({
        jobId: input.jobId, attemptId: input.attemptId, generation: input.generation,
        type: 'repository.understanding_indexed',
        payload: { snapshotId: snapshot.id, recordCount: facts.length, createdCount, reusedCount },
        producer: input.producer, idempotencyKey: `repository-understanding:${snapshot.id}`,
      });
      return indexRow(snapshot.id)!;
    },
    listRecords,
    async search(snapshotId, query, options = {}) {
      if (!query.trim()) throw new RepositoryUnderstandingError('INVALID_SEARCH_QUERY', 'Repository search query must not be empty');
      const snapshot = repository.getSnapshot(snapshotId);
      if (!snapshot) throw new RepositoryUnderstandingError('SNAPSHOT_NOT_FOUND', 'Repository snapshot not found');
      const limit = Math.max(1, Math.min(500, options.limit ?? 100));
      const normalized = query.toLowerCase();
      const records = authority.listRecords(snapshotId).filter((record) => (
        record.key.toLowerCase().includes(normalized)
        || JSON.stringify(record.payload).toLowerCase().includes(normalized)
      )).slice(0, limit);
      const lexical = await repository.search(snapshotId, query, { limit });
      return {
        snapshotId, stateDigest: snapshot.stateDigest, records,
        lexicalMatches: lexical.matches,
        truncated: records.length >= limit || lexical.truncated,
        stale: records.some((record) => record.stale) || lexical.stale,
      };
    },
    addArchitectureNote(input) {
      assertAuthority(input);
      if (latestSnapshotId(input.repositorySnapshotId) !== input.repositorySnapshotId) {
        throw new RepositoryUnderstandingError('STALE_REPOSITORY_SNAPSHOT', 'Architecture note requires the current repository snapshot');
      }
      if (!input.statement.trim()) throw new RepositoryUnderstandingError('INVALID_ARCHITECTURE_NOTE', 'Architecture note statement must not be empty');
      if (input.sourceReferences.length === 0) throw new RepositoryUnderstandingError('MISSING_SOURCE_REFERENCE', 'Architecture note requires at least one exact source reference');
      const references = input.sourceReferences.map((reference) => ({
        path: normalizeRelative(reference.path), lineStart: reference.lineStart, lineEnd: reference.lineEnd,
      }));
      for (const reference of references) {
        const entry = repository.getEntry(input.repositorySnapshotId, reference.path);
        if (!entry || entry.captureStatus !== 'captured' || reference.lineStart < 1 || reference.lineEnd < reference.lineStart) {
          throw new RepositoryUnderstandingError('INVALID_SOURCE_REFERENCE', 'Architecture note source reference is not present in the bound snapshot');
        }
      }
      const now = input.now ?? Date.now();
      const noteId = `architecture_note_${randomBytes(12).toString('hex')}`;
      db.prepare(
        `INSERT INTO repository_architecture_notes
           (note_id,job_id,attempt_id,generation,fence_token,repository_snapshot_id,statement,source_references_json,created_at)
         VALUES (?,?,?,?,?,?,?,?,?)`,
      ).run(noteId, input.jobId, input.attemptId, input.generation, input.fenceToken, input.repositorySnapshotId, input.statement.trim(), JSON.stringify(references), now);
      deps.appendJobEvent({
        jobId: input.jobId, attemptId: input.attemptId, generation: input.generation,
        type: 'repository.architecture_note_recorded', payload: { noteId, repositorySnapshotId: input.repositorySnapshotId },
        producer: input.producer, idempotencyKey: `repository-architecture-note:${noteId}`,
      });
      return authority.listArchitectureNotes(input.repositorySnapshotId).find((note) => note.noteId === noteId)!;
    },
    listArchitectureNotes(snapshotId) {
      if (!repository.getSnapshot(snapshotId)) throw new RepositoryUnderstandingError('SNAPSHOT_NOT_FOUND', 'Repository snapshot not found');
      const rows = db.prepare(
        'SELECT * FROM repository_architecture_notes WHERE repository_snapshot_id=? ORDER BY created_at,note_id',
      ).all(snapshotId) as Array<Record<string, unknown>>;
      return rows.map((row) => ({
        noteId: String(row.note_id), jobId: String(row.job_id), attemptId: String(row.attempt_id),
        generation: Number(row.generation), repositorySnapshotId: String(row.repository_snapshot_id),
        statement: String(row.statement), sourceReferences: JSON.parse(String(row.source_references_json)) as RepositorySourceReference[],
        createdAt: Number(row.created_at),
      }));
    },
  };
  return authority;
}
